### ISSUE TITLE
Place your Icons in here!

### ISSUE THREAD

**Issue by jordaninjohnson** [brentp24/strtUP#31]

**Comment by brentp24** [comment]
https://fontawesome.com/icons/utensils?style=solid

**Comment by georgegombert** [comment]
NBA Scores - https://fontawesome.com/icons/basketball-ball?style=solid
Air Quality - https://fontawesome.com/icons/lungs?style=solid

**Comment by jordaninjohnson** [comment]
CDN with my api key - <script src="https://kit.fontawesome.com/c90739eabf.js" crossorigin="anonymous"></script>

weather - <i class="fas fa-cloud-sun"></i>
quote -  <i class="fas fa-quote-right"></i>
background - <i class="far fa-image"></i>

**Comment by jordaninjohnson** [comment]
background - `<i class="far fa-image"></i>`

**Comment by jordaninjohnson** [comment]
weather - `<i class="fas fa-cloud-sun"></i>`

**Comment by jordaninjohnson** [comment]
quote - `<i class="fas fa-quote-right"></i>`
